package com.pojo;
// Generated Jul 27, 2018 11:38:02 PM by Hibernate Tools 4.3.1

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * Location generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Location implements java.io.Serializable {

    private Integer LId;
    private String zilla;
    private String thana;
    private List<String> zilla_list = new ArrayList<>();
    private List<String> thana_list = new ArrayList<>();

    public List<String> get_zillas() {
        try {
            Connection con;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rantcar", "root", "root");
            PreparedStatement prst;
            prst = con.prepareStatement("select distinct zilla from location");
            ResultSet rs = prst.executeQuery();
            while (rs.next()) {
                zilla_list.add(rs.getString("zilla"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return zilla_list;
    }

    public List<String> get_thanas() {
        try {
            Connection con;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rantcar", "root", "root");
            PreparedStatement prst;
            prst = con.prepareStatement("select thana from location where zilla = ?");
            prst.setString(1, getZilla());
            ResultSet rs = prst.executeQuery();
            while (rs.next()) {
                thana_list.add(rs.getString("thana"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return thana_list;
    }

    public List<String> getZilla_list() {
        return zilla_list;
    }

    public void setZilla_list(List<String> zilla_list) {
        this.zilla_list = zilla_list;
    }

    public List<String> getThana_list() {
        return thana_list;
    }

    public void setThana_list(List<String> thana_list) {
        this.thana_list = thana_list;
    }

    public Location() {
    }

    public Location(String zilla, String thana) {
        this.zilla = zilla;
        this.thana = thana;
    }

    public Integer getLId() {
        return this.LId;
    }

    public void setLId(Integer LId) {
        this.LId = LId;
    }

    public String getZilla() {
        return this.zilla;
    }

    public void setZilla(String zilla) {
        this.zilla = zilla;
    }

    public String getThana() {
        return this.thana;
    }

    public void setThana(String thana) {
        this.thana = thana;
    }

}
