package com.pojo;
// Generated Jul 27, 2018 11:38:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * RentDetails generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class RentDetails  implements java.io.Serializable {


     private Integer RId;
     private int VName;
     private String driverName;
     private String userName;
     private String startLocation;
     private String endLocation;
     private Date rentDate;
     private double rentCost;

    public RentDetails() {
    }

    public RentDetails(int VName, String driverName, String userName, String startLocation, String endLocation, Date rentDate, double rentCost) {
       this.VName = VName;
       this.driverName = driverName;
       this.userName = userName;
       this.startLocation = startLocation;
       this.endLocation = endLocation;
       this.rentDate = rentDate;
       this.rentCost = rentCost;
    }
   
    public Integer getRId() {
        return this.RId;
    }
    
    public void setRId(Integer RId) {
        this.RId = RId;
    }
    public int getVName() {
        return this.VName;
    }
    
    public void setVName(int VName) {
        this.VName = VName;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getStartLocation() {
        return this.startLocation;
    }
    
    public void setStartLocation(String startLocation) {
        this.startLocation = startLocation;
    }
    public String getEndLocation() {
        return this.endLocation;
    }
    
    public void setEndLocation(String endLocation) {
        this.endLocation = endLocation;
    }
    public Date getRentDate() {
        return this.rentDate;
    }
    
    public void setRentDate(Date rentDate) {
        this.rentDate = rentDate;
    }
    public double getRentCost() {
        return this.rentCost;
    }
    
    public void setRentCost(double rentCost) {
        this.rentCost = rentCost;
    }




}


