package com.pojo;
// Generated Jul 27, 2018 11:38:02 PM by Hibernate Tools 4.3.1


import com.util.HibernateUtil;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;




/**
 * Users generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Users  implements java.io.Serializable {


     private Integer UId;
     private String UName;
     private String password;
     private String email;
     private String phone;

    public Users() {
    }

    public Users(String UName, String password, String email, String phone) {
       this.UName = UName;
       this.password = password;
       this.email = email;
       this.phone = phone;
    }
    
    public boolean logout(){
      
     return  true;
    }
    
     public boolean login() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        String sql = "select al from Users al where UName= :userName and password= :password ";
//        String sql = "from Users where userName= :userName and password= :password";
        Query quary = session.createQuery(sql);
        quary.setString("userName", UName);
        quary.setString("password", password);
        List a = quary.list();
        int b = a.size();
        if (b == 1) {
            return true;
        } else {
            return false;
        }
    }
   
      public boolean addUser() {
        Users user = new Users(getUName(), getPassword(), getEmail(), getPhone());
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.save(user);
        session.getTransaction().commit();
        session.close();
        return true;
    }
    public Integer getUId() {
        return this.UId;
    }
    
    public void setUId(Integer UId) {
        this.UId = UId;
    }
    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


